(source gnu)
(source marmalade)
(source melpa)

(depends-on "auto-complete")
(depends-on "auto-async-byte-compile")
(depends-on "cask")
(depends-on "fringe-helper")
(depends-on "helm")
(depends-on "helm-migemo")
(depends-on "init-loader")
(depends-on "migemo")
(depends-on "mmm-mode")
(depends-on "popup")
(depends-on "popwin")
(depends-on "undo-tree")

;; prog modes
(depends-on "auto-complete-emacs-lisp")
(depends-on "c-eldoc")
(depends-on "cider")
(depends-on "clojure-mode")
(depends-on "cmake-mode")
(depends-on "eldoc-extension")
(depends-on "google-c-style")
(depends-on "haskell-mode")
(depends-on "js2-highlight-vars-mode")
(depends-on "js2-mode")
(depends-on "markdown-mode")
(depends-on "php-mode")
(depends-on "paredit")
(depends-on "rcodetools")
(depends-on "rvm")

;; custom theme
(depends-on "moe-theme")
(depends-on "tango-2-theme")
(depends-on "twilight-theme")
(depends-on "pastels-on-dark-theme")
