;; -*- coding:utf-8 mode:emacs-lisp -*-
(source gnu)
(source marmalade)
(source melpa)

(depends-on "ac-dabbrev")
(depends-on "ac-c-headers")
(depends-on "auto-complete")
(depends-on "auto-async-byte-compile")
(depends-on "cask")
(depends-on "fringe-helper")
(depends-on "helm")
(depends-on "helm-git-grep")
(depends-on "helm-migemo")
(depends-on "init-loader")
(depends-on "migemo")
(depends-on "popup")
(depends-on "popwin")
(depends-on "undo-tree")

;; prog modes
(depends-on "c-eldoc")
(depends-on "cider")
(depends-on "clojure-mode")
(depends-on "cmake-mode")
(depends-on "eldoc-extension")
(depends-on "flycheck")
(depends-on "flycheck-pos-tip")
(depends-on "google-c-style")
(depends-on "haskell-mode")
(depends-on "js2-mode")
(depends-on "js2-highlight-vars" :git "https://github.com/skiviharju/js2-highlight-vars-mode.git")
(depends-on "js-doc")
(depends-on "json-mode")
(depends-on "markdown-mode")
(depends-on "php-mode")
(depends-on "paredit")
(depends-on "rainbow-delimiters")
(depends-on "ruby-mode")
(depends-on "ruby-block")
(depends-on "ruby-end")
(depends-on "web-mode")

;; custom theme
(depends-on "moe-theme")
(depends-on "tango-2-theme")
(depends-on "twilight-theme")
(depends-on "pastels-on-dark-theme")
(depends-on "molokai" :git "https://github.com/hbin/molokai-theme.git")
