;; detect OS
(defvar run-linux (equal system-type 'gnu/linux))
(defvar run-darwin (equal system-type 'darwin))

;; detect window system
(defvar run-cli (equal window-system nil))
(defvar run-cocoa (equal window-system 'ns))
(defvar run-carbon (equal window-system 'mac))

(setq inhibit-startup-message t)
(setq ring-bell-function '(lambda ()))
(setq make-backup-files nil)
(setq delete-auto-save-file t)
(setq auto-save-default nil)
(delete-selection-mode 1)
(setq-default indent-tabs-mode nil)
(global-set-key "\C-h" 'delete-backward-char)
(show-paren-mode 1)
(global-font-lock-mode t)
(setq-default transient-mark-mode t)
(require 'font-lock)
(prefer-coding-system 'utf-8)
(setq scroll-step 1)
(setq truncate-partial-width-windows nil)
(blink-cursor-mode 0)
(recentf-mode t)
(setq large-file-warning-threshold (* 25 1024 1024))
(defalias 'yes-or-no-p 'y-or-n-p)
(setq gc-cons-threshold (* 10 gc-cons-threshold))
(setq completion-igno t)
(global-auto-revert-mode 1)
(global-set-key "\C-cg" 'goto-line)
(global-set-key "\C-cc" 'comment-or-uncomment-region)
